### PR TITLE
Change `lib.mkIf config.enable' to `lib.mkIf cfg.enable'

### PR DESCRIPTION
**Pull request by sylvorg**

### CODE REVIEW

**Comment by sylvorg** [comment]
Ah, screw; the commit messages got muddled...

**Comment by K900** [comment]
Thanks! Things got a little confused when I was recovering this stuff from my old config...

**Comment by sylvorg** [comment]
No problem! Though I'd appreciate it if you could tell me how to actually _use_ this! 😅

**Comment by K900** [comment]
Just adding the module to your NixOS config should be enough.

**Comment by sylvorg** [comment]
I did so and then tried to attach VSCode to NixOS, but it just downloaded the server and tried _that_ way.

**Comment by K900** [comment]
It should download the server, yes, and then systemd should catch that and run the script to replace the node binary with the nixpkgs-provided one.

**Comment by sylvorg** [comment]
At the moment the process errors out with `node: cannot execute: required file not found`.

**Comment by K900** [comment]
What does `systemctl --user status vscode-remote-workaround` output?

**Comment by sylvorg** [comment]
Interesting... It seems to be working now... I guess I just needed to shut down the VM.

**Pull request merged**
